name: ERT Tests

on:
  workflow_dispatch:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version:
          - "28.2"
          - "29.4"
          - "snapshot"
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - name: Run ERT tests
        run: |
          emacs -batch \
            -L . \
            -l ert \
            -l read-later.el \
            -l tests/test_runner.el \
            -f ert-run-tests-batch-and-exit
